source 'https://rubygems.org'

group :development do
  gem 'pry'
  gem 'pry-coolline' #realtime colorize
  gem 'pry-theme' #colorscheme
  gem 'pry-doc'
  gem 'pry-clipboard'
  gem 'awesome_print'
  gem 'gem-browse'
  # for rails
  gem 'pry-rails'
  gem 'hirb-unicode' #`rails c`=>`Hirb.enable`
  # for test
  gem 'guard-shell'
  gem 'guard-livereload'
  # process control
  gem 'foreman'
end
