source :rubygems

gem 'ruby-debug19', :require => 'debug'

gem 'pry'
gem 'pry-coolline' #realtime colorize
gem 'pry-theme' #colorscheme
gem 'pry-doc'
gem 'debugger-pry', :require => 'debugger/pry' #add pry command to rdb session
gem 'pry-debugger' #add debugger commands
gem 'pry-rails'


gem 'awesome_print'
